linters:
  - eslint --ignore-path .gitignore .
  - jscs .
  - jshint . --verbose
  - markdownlint *.md
  - proselint *.md
  - remark *.md --quiet --frail --no-stdout
  - yamllint -c yamllint.yml .
  - write-good *.md
  - sh test/colors.sh
